use crate::syntax::{ParseTree, Token};

#[derive(Debug)]
pub enum ParsingError {
    EmptyInput,
    ExpectedLexeme,
    ExpectedNumberToken { found: Option<Token> },
    ExpectedIdentifierToken { found: Option<Token> },
    ExpectedColonToken { found: Option<Token> },
    ExpectedDataTypeToken { found: Option<Token> },
    ExpectedAssignToken { found: Option<Token> },
    ExpectedKeywordToken { found: Option<Token> },
    ExpectedExpression { found: Option<ParseTree> },
    ExpectedIdentifier { found: Option<ParseTree> },
    ExpectedDataType { found: Option<ParseTree> },
    ExpectedDeclKeyword { found: Option<ParseTree> },
    ExpectedAssignment { found: Option<ParseTree> },
    ExpectedTerm { found: Option<ParseTree> },
    ExpectedFactor { found: Option<ParseTree> },
    ExpectedLiteral { found: Option<ParseTree> },
    ExpectedNumber { found: Option<ParseTree> },
    ExpectedDeclaration { found: Option<ParseTree> },
    ExpectedStatement { found: Option<ParseTree> },
    ExpectedStatementList { found: Option<ParseTree> },
    ExpectedLeftParen { found: Option<Token> },
    ExpectedRightParen { found: Option<Token> },
    ExpectedLeftCurl { found: Option<Token> },
    ExpectedRightCurl { found: Option<Token> },
    ExpectedBlock { found: Option<ParseTree> },
    ExpectedSemicolon { found: Option<Token> },
    ExpectedParameter { found: Option<ParseTree> },
    ExpectedParameterList { found: Option<ParseTree> },
    ExpectedReturnType { found: Option<ParseTree> },
    ExpectedRightArrowToken { found: Option<Token> },
    FailedToParseInteger,
}
